# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-08 04:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('np', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.CharField(default=datetime.datetime(2016, 6, 8, 4, 21, 28, 706195, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
