# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-08 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('np', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('New Zealand', 'New Zealand'), ('World', 'World'), ('Technology', 'Technology'), ('Sport', 'Sport')], default='New Zealand', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
